modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "origins-expansion"
version = "${version}"
displayName = "Origins Expansion"
authors = "EdwinMindcraft"
description = '''
Adds additional hooks for origins datapacks
'''
#logoFile = ""

[[dependencies.origins-expansion]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.origins-expansion]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.origins-expansion]]
modId = "architectury"
mandatory = true
versionRange = "[1.10.142,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.origins-expansion]]
modId = "origins"
mandatory = true
versionRange = "[0.7.1,)"
ordering = "AFTER"
side = "BOTH"